chains:
  gaia-testnet:
    key: gaia
    chain-id: GAIA
    rpc-addr: http://38.242.229.138:11657
    grpc-addr: http://38.242.229.138:11090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: stride
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://38.242.229.138:25657
    grpc-addr: http://38.242.229.138:25090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
